### ISSUE TITLE
Not an issue - but a thank you

### ISSUE THREAD

**Issue by sietec** [D0m0/CocoaTop#1]
@D0m0 - I just wanted to take the time to thank you for sharing your ingenious code with all of us to gain insights from.  I have wanted to contribute to CocoaTop since it was released in Cydia many years ago now, and kept checking for whether it had been open sourced yet or not.

You kept your promise and opened it up, I thank you and know that many, many others do as well.

The simple brilliance in this app is amazing.  While I could nitpick at stupid things like sizing of the UX on an iPad Pro, etc., that would be counter-productive.  The application was built so well, it has survived (what is it, 5 or 6 versions???) many major iOS releases and _still works great_ to this day!

Thanks again for your contribution.  I am going to work on the UI for larger devices and, should I make any significant progress, I'll share with you or submit a PR.

@D0m0 Please feel free to close this issue at any time or even delete it - since there was no wiki setup, I didn't know how else to thank you...I don't want people thinking there are issues with your code!

**Comment by D0m0** [comment]
Wow, thanks! This is very heart-warming, and I'm glad you like CocoaTop. But what's more important is that you (and maybe others, too) will bring life back into this project! It becomes kinda abandoned with the release of iOS 11 and 12. I don't want to put constraints, so feel free to make any major/minor changes to code and dialogs. If you submit PRs I'll try to react more quickly!

**Comment by sietec** [comment]
Awesome, thanks @D0m0 - I cannot explain what a wonderful resource it has been - keep in mind I am a "never GUI ... always CLI guy" but on a constrained system such as iOS, CocoaTop is by far the absolute best process viewer I have seen.  Not to mention (with a few hacks for later versions of iOS) its stability is rock solid, your 'first project' is quite impressive.

I'm going to get busy working on some updates for UX first, primarily to make use of the larger screen real-estate on iPads (Pro's in particular) and to integrate it with the system's dynamic type font size system.

Thanks for the response.  I'll be in touch.

**Comment by D0m0** [comment]
:thumbsup:

**Comment by badger200** [comment]
I literally can’t live without CocoaTop, I use it many times every single day. I’m the kind of Windows (and Mac) power user who habitually checks my Task Manager/Process Explorer/Process Hacker 2/Activity Monitor.

I’d gladly donate a few bucks if you have a PayPal or similar donate link set up.

**Comment by D0m0** [comment]
> I’m the kind of Windows (and Mac) power user who habitually checks my Task Manager/Process Explorer/Process Hacker 2/Activity Monitor

Exactly the reason why I made CocoaTop, implying that I felt like I **could** do it in the first place!

> if you have a PayPal or similar donate link set up

When the right time comes ;)

P.S. I appreciate that you posted some known issues here. I abandoned CocoaTop due to absence of spare time, but maybe I'll post some tips on resolving them if someone else comes along and takes the lead!

**Comment by sietec** [comment]
Just an update on this, I have sorted out several issues (tested on a very limited number and variety of devices...) and should have a PR ready within a week or so (maybe 2, for more thorough testing). I'll update this thread, and create a PR when able if @D0m0 is good with that. 

Thanks again for open sourcing this SWWEEEETTT app, I am really excited to bring dark mode and (a limited amount of, at this time) bug 🐛 fixes. It's really a well written app considering it was designed for iOS, what? 8? 

sietecFAST™

**Comment by D0m0** [comment]
Sorry for not replying right away. I would really like you to release your update! This was exactly why I open-sourced it and finally it is happening! I am not limiting any kind of activity, as long as it remains open-source and free.

**Comment by sietec** [comment]
@D0m0 No worries my friend, I have been working on this as often as possible in my spare time and have made some, relatively significant, strides. So far:

- Fixed rotation fencing and boundary assertions on large (tested on iPad Pro 9.1 and 12.9) devices. 
  - Related to this, adjusted font, table views (and the entire related sub-hierarchy…e.g. NSTableViewCells, etc.)
- Partially mitigated segfault on selecting to view modules in the process details view, including logic that writes a flag to a newly added serialized file indicating that:
  - We are about to go into a process's detailed view (or are switching from one detail to another … e.g. summary to open files/descriptors) and including the timestamp, process of interest, place we are switching from (…willResignActive…) and to (the users selected choice) with, most importantly a flag (C struct) serialized to our atomic file, that records the beginning, intermediate and (if reached without abort) final destination.
  - The next time the app is launched, we check this file. If the app failed prior to entering a success into the destination process view, automatically revert preferences to the previous (if exists) success or the app defaults for process inspection. This keeps a never ending crash from occurring without the user having to manually edit the CocoaTop plist holding this information in order to ever successfully view the details of a process again. 
- Dark mode in progress
- Creating a few separate versions of this app targeting different hardware and firmware, in order to clean up some of the (IMHO often error prone Device and version check macros) that, as time goes on, will become unwieldy. 

Please let me know if you're aware of more important or time critical issues that I should devote more time to. 

Thanks. I will update soon. 

sietecFAST™ ∞

**Comment by D0m0** [comment]
This is super cool!!

> Creating a few separate versions of this app

Do we really need that? You could just scrap the old code, leaving only the iOS10+ version.

> Thanks. I will update soon.

Are you planning to only release the .deb, or will you put it on Cydia?
