### ISSUE TITLE
Create new branch for 32 bit

### ISSUE THREAD

**Issue by NSExceptional** [D0m0/CocoaTop#12]
Instead of just putting "check out a 2019 commit" in the readme, how about choosing the latest commit that supported 32 bit and making a new branch with it named `32bit` or something? :)

**Comment by NSExceptional** [comment]
This would also allow us to remove a bunch of the commented-out code that is clearly left behind so that someone can uncomment it if they want to take the astronomical effort to get the project to compile for < iOS 6 again:

```objc
//#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_6_0
```

A dedicated 32 bit branch would really help clean up the codebase

**Comment by D0m0** [comment]
I fully agree!
