### ISSUE TITLE
Fails to handle device rotation/orientation changes properly 

### ISSUE THREAD

**Issue by badger200** [D0m0/CocoaTop#2]
On both iPad and iPhone iOS 12.4, CocoaTop 64-bit has a weird glitch where it remains stuck in the original orientation. 

But if you open Task switcher and open another app, then switch back to CocoaTop, that triggers CT to redraw its UI correctly in the new orientation.

**Comment by D0m0** [comment]
This is due to the following methods of UITableViewController being deprecated by Apple:

- shouldAutorotateToInterfaceOrientation
- didRotateFromInterfaceOrientation

Work needs to be done to properly handle orientation using modern methods.

**Comment by sietec** [comment]
@D0m0 A long time ago I offered to help out with this project and failed to find the time to do so, I will be working on the mouse commonly reported bugs, and some i've found, and will submit a PR once done. Thanks again for open sourcing this bad ass 😎 project!

**Comment by badger200** [comment]
> This is due to the following methods of UITableViewController being deprecated by Apple:
> 
> * shouldAutorotateToInterfaceOrientation
> * didRotateFromInterfaceOrientation
> 
> Work needs to be done to properly handle orientation using modern methods.

What about the Properties of UIWindow:
BOOL _usesLegacySupportedOrientationChecks
BOOL _legacyOrientationChecks 
?

I'm just hacking with FLEXing but these sound promising at least.

**Comment by D0m0** [comment]
Did you check [this fork](https://github.com/CRKatri/CocoaTop13)? It could already be fixed there.
