### ISSUE TITLE
Ports screen freezes CocoaTop, MobileSubstrate 7101 may fix 

### ISSUE THREAD

**Issue by badger200** [D0m0/CocoaTop#3]
On CocoaTop 64 2.0.2+debug, the Ports feature no longer works (in iOS 10.2.1 it worked). It instantly freezes the app every time.

Unc0ver 3.8.0b1. iOS 12.4. MobileSubstrate 0.9.7100b4. iPhone 6 (7,2), iPad Pro 9.7” (iPad6,3 / j127ap).

HOWEVER with unc0ver 4.0.3 (possibly all unc0ver v4? Or is it MobileSubstrate 0.9.7101? See note below) now the Ports WORKS again for the first time in 64-bit, but now the Modules for SpringBoard doesn’t work, and displays both empty and red (as if the SB process has terminated, even though it hasn’t). 

I’m not sure what changed in unc0ver. 

NOTE: I might be mixing up unc0ver with MobileSubstrate! There is a new MobileSubstrate 0.9.7101 updating the long-standing 0.9.7100b4(?) that I also recently tried separately from unc0ver v4. 

So it was either the MobileSubstrate 7100 -> 7101 update, or the unc0ver 3.8.0b1 -> 4.0.3 update that caused Ports to begin working again.

**Comment by D0m0** [comment]
Fixed
