### ISSUE TITLE
CocoaTop wont open

### ISSUE THREAD

**Issue by Frostbourn** [D0m0/CocoaTop#6]
Hi

CocoaTop worked like a charm on 13.4 but after upgrading to 13.4.1 it accidentaly closes just after the open. How can I fix this issue?

Regards

**Comment by D0m0** [comment]
Try using this fork, it is being maintained:
https://github.com/CRKatri/CocoaTop

**Comment by CySxL** [comment]
> Try using this fork, it is being maintained:
> https://github.com/CRKatri/CocoaTop

How can I install Cocoatop after open that link in Safari?

**Comment by badger200** [comment]
> > Try using this fork, it is being maintained:
> 
> > https://github.com/CRKatri/CocoaTop
> 
> 
> 
> How can I install Cocoatop after open that link in Safari?

I’d like to know also. It seems like this might merely be source code, with no binaries or .deb packages posted whatsoever. Which would be very unfortunate because probably the ratio of people using CocoaTop to the number capable of compiling it from source is surely at least 100:1 or worse.

**Comment by D0m0** [comment]
Guys, I've created a release. If someone could install the .deb on iOS 13.4.1 or above and test it, then we could close this issue!

**Comment by badger200** [comment]
@D0m0 Can we publish a proper “Release” in GitHub? I’m not experienced enough to know the proper term but I’ve never had to dig so hard to find a release deb before. I could only find the .deb inside code under packages or Debian or something.

The typical user visiting this github would have no idea CocoaTop has received an incredible update.

**Comment by D0m0** [comment]
I created the release on [my github page](https://github.com/D0m0/CocoaTop), not on CRKatri's
