### ISSUE TITLE
Incredible fork with full iOS 6-13 support, iPad Split View, Dark Mode!

### ISSUE THREAD

**Issue by badger200** [D0m0/CocoaTop#7]
I’d kill to get a binary or package of this!! 

https://github.com/SongXiaoXi/CocoaTop

**Comment by D0m0** [comment]
I think I still have the toolchain intact, I'll see if I can build it!

  11.10.2020, 09:58, badger200 <notifications@github.com>

  I’d kill to get a binary or package of this!!

  https://github.com/SongXiaoXi/CocoaTop

**Comment by badger200** [comment]
@D0m0 Awesome!! I’m adding your repo d0m0.github.io so hopefully I don’t miss it if you can build it! 

Thanks a million, I’ll gladly donate via PayPal if you can succeed. Let me know where I can donate if so.

**Comment by Randomblock1** [comment]
Hey, I managed to get GitHub Actions to build that fork and make some usable deb files every time something is updated or changed. See #8.

**Comment by D0m0** [comment]
> Hey, I managed to get GitHub Actions to build that fork and make some usable deb files every time something is updated or changed. See #8.

You're awesome, man!

I didn't know it was possible, so I took a look at your Actions file, and it's magnificent. Good job!
