### ISSUE TITLE
Wrong CFBundleIdentifier

### ISSUE THREAD

**Issue by Randomblock1** [D0m0/CocoaTop#9]
This makes the plist file generate wrong. Fixing it would fix preferences.
https://github.com/D0m0/CocoaTop/blob/c7ab21bb488e13a0e5926620eb71e7fc3e65a571/src/res/Info.plist#L21

**Comment by badger200** [comment]
Is this in response to my big comment on the iOS 13 commit I made moments ago about this exact issue? Or just a huge coincidence? (Bc wow that was fast)

**Comment by Randomblock1** [comment]
Yep. I didn't really look too hard into what was changed, I missed this one. I think this is the only change we need to make to make it fully compatible as an upgrade.
